'Everything that starts with a simple quote 'is a comment. You can also put comments on several lines using/'to start and '/to end.

'Start of UML diagram
@startuml
header CVX-AI - VueJS Frontend
title HomePage.vue

skinparam style strictuml
skinparam SequenceMessageAlignment justified
skinparam MaxMessageSize 100
scale 1

actor User
User -> Website: opens
activate Website
activate "Web Server"
activate "Filesystem Server"
database "PC Filesystem"
activate "PC Filesystem"
Website -> "Web Server": initialize
note right of Website
http://localhost:8080/
end note
Website -> "Filesystem Server": initialize
note right of Website
http://localhost:8090/
end note
"Filesystem Server" -> "PC Filesystem": read

"PC Filesystem" --> "Filesystem Server": return default directory
note left of "PC Filesystem"
.../CVX_AI_WebUI/root/api/data/"
end note
"Filesystem Server" --> Website: provide directories
Website --> User: display Syncfusion FileManager component
deactivate Website
deactivate "Filesystem Server"
deactivate "PC Filesystem"
@enduml
